### ISSUE TITLE
Decide on `Nft` and `Collection` sizes

### ISSUE THREAD

**Issue by vpontis** [glow-xyz/nftoken#17]
Goal: it's > 2x cheaper to use this program than SPL Token + Metaplex

## SPL + Metaplex Costs

<table>
<tr>
	<td>Account
	<td>Size
	<td>Cost
<tr>
	<td>Mint
	<td>82
	<td>$0.15
<tr>
	<td>Token
	<td>165
	<td>$0.20
<tr>
	<td>Metadata
	<td>679
	<td>$0.56
<tr>
	<td>Edition / Standard
	<td>40
	<td>$0.12
<tr>
	<td>Total
	<td>~ 980
	<td>~ $1.02
</table>

## Nftoken

500 bytes → ~ $0.44

- holder - 32
- creator - 32
- creator_can_update - 1
- name - 32
- image_url - 128
- metadata_url - 128
- collection - 32
- delegate - 32
- created_at - 8

How to cut? — URLs are by far the most expensive part. How short can we make them while still being compatible with IPFS / Arweave?

And how do we give ourselves flexibility to add more things later on? Or do we just do that by versioning and allow upgrading the version number? 

That's another big question:

- how do we migrate an account to a new version?
- will Solana allow resizing an account in the future?
- does this impact our use of PDAs vs Keypairs?

**Comment by crypt0miester** [comment]
I believe the created_at can be removed, because the txn blocktime of the minted nft is recorded thus not needed. 

image_url is not needed since it can be fetched from metadata_url. 

this is my two cents. thanks, and keep up the good work.
