### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by aleixisp** [glow-xyz/nftoken#201]
Any plans to add a small SDK for python to interact with the program in the roadmap?

Or better details on how to build transactions would love to integrate this token into my current flow of issuing tokens at purchase.

**Comment by aleixisp** [comment]
Expanding here, could it be possible to provide the IDL file from the Anchor framework?

**Comment by vpontis** [comment]
Hi!

- Python — Not planning on adding it, but you could add a PR!
- IDL — You can create the IDL file by running anchor build, but I should check it in. I'll do that soon!
